### ISSUE TITLE
Fix FSK-Lab for new release

### ISSUE THREAD

**Issue by schuelet** [RakipInitiative/ModelRepository#101]
issues to be fixed:

- make sure, old models (<1.04) and RAKIP models work with FSK-Lab
- fix #425 (Silebat/FSK-Lab): node settings don't load on reset

- build needs to pass complete testing pipeline
- provide official support for KNIME 4.X (and after release remove the warning here: https://foodrisklabs.bfr.bund.de/fsk-lab/ ).

**Comment by mfilter** [comment]
please add to the list: 
- provide official support for KNIME 4.X (and after release remove the warning here: https://foodrisklabs.bfr.bund.de/fsk-lab/ ).
