### ISSUE TITLE
Implement auto pick interpreter for Python in FSK-Lab

### ISSUE THREAD

**Issue by schuelet** [RakipInitiative/ModelRepository#112]
Depending on the model, FSK-Lab needs to tell KNIME, which version (2 or 3) of python is used. 

- modeller needs to specify in the fiels "language_written_in" which language specifically was used for the script

**Comment by schuelet** [comment]
- development blocked by API changes made in KNIME 4
  - python support does not work in KNIME 4 when developin on target-platform 3.7

- work will resume, until FSK-Lab migration to target-platform 4

**Comment by schuelet** [comment]
The problem is now fixed for KNIME 4.x. 
- Testing can be done with release candidate 2.0:
- FSK-Lab built on KNIME 4 platform: [https://dl.bintray.com/fsk/2.0.0-rc1](https://dl.bintray.com/fsk/2.0.0-rc1)

(TODO: we need to change the actual version number to 2.0)

**Comment by mfilter** [comment]
@schuelet : please clarify what (TODO: we need to change the actual version number to 2.0) implies.
in the given link there is nothing to install!

**Comment by Thatsreallycool** [comment]
Download worked fine for me, testing starts

**Comment by Thatsreallycool** [comment]
Wrote a little python fskx file, that plots the current used version of python kernel as text. If you change the field  "language_written_in"  in the editor, the image plot changes between python 2 and 3 👍 
for completeness i attached the created fskx file for future tests
[pychoosertest.zip](https://github.com/RakipInitiative/ModelRepository/files/5300788/pychoosertest.zip)

**Comment by Thatsreallycool** [comment]
after thought: would recommend a python installation tutorial for local installation, because both anacondas python_knime environments and all necessary packages have to be installed properly for it to work. 
If this needs only to work on a preconfigured server this is already fine in the current state

**Comment by Thatsreallycool** [comment]
update on testing from Petra and Marcel: 
If the user only enters "python      " or "python 10" or "python 32" in the field "language_written_in", py3 is chosen by FSK-Lab. 
Is this working as intended?

**Comment by schuelet** [comment]
TODO: we need to change the actual version number to 2.0: 
related to #150

**Comment by mfilter** [comment]
Is this an issue that needs review or is this work in progress?

**Comment by schuelet** [comment]
working as intended. Closing the issue.

**Comment by schuelet** [comment]
Reopening the ticket for additional testing: 

You can use the following test workflow to check if the feature works. Also available on KNIME server under FSKX_Testing.

[https://app.zenhub.com/files/241333403/4d07b50c-791b-468b-bb05-5844c15c2a63/download](https://app.zenhub.com/files/241333403/4d07b50c-791b-468b-bb05-5844c15c2a63/download)

Requirements: 
- pyhton 3.x and python 2.7 with pandas & numpy already installed. 
- KNIME Python Integration installed
- [FSK-Lab 2.0.0-rc ](https://dl.bintray.com/fsk/2.0.0-rc1)

**Comment by schuelet** [comment]
this is now outdated. In the future we need to auto-pick Conda environments, which will be a different ticket.
