### ISSUE TITLE
Python modell made in icpmf can't be read in 1.8.1

### ISSUE THREAD

**Issue by schuelet** [RakipInitiative/ModelRepository#115]

**Comment by schuelet** [comment]
Tested on Windows

**Comment by mfilter** [comment]
@miguelalba  Is this already available for testing now? If yes, please assign it to Petra and Marcel. Thx

**Comment by ganasp** [comment]
Tested on my APS (Windows). Nodes FSKX Reader, FSK Editor JS, FSK Runner and FSKX Writer worked perfectly for starting workflow with reading a fskx file generated with icpmf.
