### ISSUE TITLE
FSK Writer throws error when loaded without valid destination 

### ISSUE THREAD

**Issue by schuelet** [RakipInitiative/ModelRepository#120]
When a FSK-Writer node is not configured, i.e. no destination path has been given, the workflow can't be opened without getting the error messages below. This should be instead just be a warning.

ERROR	 ModalContext Node	 Loading model settings failed: No destination location provided! Please enter a valid location.
ERROR	 ModalContext LoadWorkflowRunnable	 Errors during load: Status: Error: fsk_lab_test_wf 0 loaded with errors
ERROR	 ModalContext LoadWorkflowRunnable	   Status: Error: fsk_lab_test_wf 0
ERROR	 ModalContext LoadWorkflowRunnable	     Status: Error: FSKX Writer 0:15
ERROR	 ModalContext LoadWorkflowRunnable	       Status: Error: Loading model settings failed: No destination location provided! Please enter a valid location.

**Comment by miguelalba** [comment]
@schuelet since we have multiple versions of the writer nodes because of the deprecated nodes, please include the node factory and if possible a minimal workflow.
