### ISSUE TITLE
FSK Reader throws error when loaded without a file path 

### ISSUE THREAD

**Issue by schuelet** [RakipInitiative/ModelRepository#121]
A workflow with a FSK-Reader can't be opened without error messages if the Reader is not configured, i.e. has no file to load in the configuration dialog.

ERROR	 ModalContext Node	 Loading model settings failed: No destination location provided! Please enter a valid location.
ERROR	 ModalContext LoadWorkflowRunnable	 Errors during load: Status: Error: KNIME_project4 3 loaded with errors
ERROR	 ModalContext LoadWorkflowRunnable	   Status: Error: KNIME_project4 3
ERROR	 ModalContext LoadWorkflowRunnable	     Status: Error: FSKX Reader 3:1
ERROR	 ModalContext LoadWorkflowRunnable	       Status: Error: Loading model settings failed: No destination location provided! Please enter a valid location.

**Comment by miguelalba** [comment]
@schuelet since we have multiple versions of the reader node because of the deprecated nodes, please include the node factory and if possible a minimal workflow.

**Comment by miguelalba** [comment]
try {
      CheckUtils.checkSourceFile(settings.getString("filename"));
    } catch (InvalidSettingsException err) {
      setWarningMessage(err.getMessage());
    }

Check how the table reader is implemented
