### ISSUE TITLE
Adding a “Resource“-tab for online creation of FSK-ML models

### ISSUE THREAD

**Issue by schuelet** [RakipInitiative/ModelRepository#13]
### Current State:
- The online model repository allows the creation and editing of FSK-ML models. However, currently it only supports to add code for the model- and the visualization-scripts. Should these scripts require additional data from other files (e.g. excel sheets or csv), there is no way to attach them to the model when using the online service.
### Goal:
- Creating or Editing a model is done in the FSK-Editor node. This node has an additional tab “Resources” that allows users to upload the files the model script needs to run.

### Concept:
- The FSK-Editor will get a new “Resources” tab.
### Implementation:
- The “Resources” tab uses the KNIME REST API to create temporary folders on the server that stores all files uploaded by the user. These files will be added to the FSK-ML model.

### Challenges:
- The developer can’t test the implementation because of missing KNIME server licenses

### Resources:
- Available: 1 developer
- Implementation: 15 days
- Testing: 3-5 days

### Total Cost:
- 20 days

**Comment by ahmadswaid** [comment]
done as of https://github.com/SiLeBAT/FSK-Lab/pull/879
