### ISSUE TITLE
put deprecated nodes in the same feature with FSK-Lab

### ISSUE THREAD

**Issue by schuelet** [RakipInitiative/ModelRepository#141]
automatically install deprecated node without the need to install deprecated nodes separatly.

**Comment by miguelalba** [comment]
The feature *de.bund.bfr.knime.fsklab.legacy.feature* is to be removed. Its plugin *de.bund.bfr.knime.fsklab.deprecatednodes* will be included in the feature *.de.bund.bfr.knime.fsklab.feature.*

**Comment by miguelalba** [comment]
@mfilter and @llavall, who should we assign this ticket to for testing?
