### ISSUE TITLE
Release Candidate 2 for v.2.0.0 ready for testing

### ISSUE THREAD

**Issue by schuelet** [RakipInitiative/ModelRepository#156]
available here: [https://dl.bintray.com/fsk/2.0.0-rc2](https://dl.bintray.com/fsk/2.0.0-rc2)

- new fixes/features:
  - no longer supported by KNIME 3.x
  - deprecated nodes are packaged within FSK-Lab, no extra install necessary any more
  - python models should pick the interpreter version mentioned in the model metadata ( "language written in")
  - FSK-Lab should auto install required R packages on Mac

**Comment by miguelalba** [comment]
RC 2.0.0-rc2 https://dl.bintray.com/fsk/2.0.0-rc2

**Comment by ganasp** [comment]
Testing https://dl.bintray.com/fsk/2.0.0-rc2 regarding picking python interpreter version according to metadata for "language written in"
for the controlled vocabularies: 
Python 3.4.8 ->  Execute performed, Python Version 3
Python 3.1.0 -> Execute performed, Python Version 3
Python 2.0.1 -> Execute failed -> therefore, no Python Version 2
other entries, not belonging to the controlled vocabularies:
Python 2.0.space character -> Execute failed
Python 2.0.0 -> Execute failed
Python 2space character -> Execute failed
Python 3space character -> Execute performed, Python Version 3
Python n-times space character -> Execute performed, Python Version 3 -> Is that as expected?
Python 5 -> Execute performed, Python Version 3 -> Is that a expected?

**Comment by schuelet** [comment]
@ganasp : Thanks for the thorough testing. Maybe I will be more forthcoming with the limitations of our implementations in the future.

- The "auto pick" only distinguishes "python 2" from "python 3", as in "python 3.1.0" is absolutely the same as "python 3.4" or "python 3WHATEVERELSE".

- Furthermore, if your PC does not have a working python 2 installation the execution will fail. You can check that, if you have a "python source" node execute the lines:
`import matplotlib.pyplot as plt
plt.plot(10)`

- I noticed, that on our work PC's the python 2 environment will always fail when trying to execute "plt.plot()". This is not related to FSK-Lab and I will send another IT message. My last one seems to have been ignored.

- last, yes, if your language_written_in starts with "py", FSK-Lab autmatically picks the interpreter you have set to default in the KNIME-Python- Settings.

- good job

**Comment by mfilter** [comment]
@schuelet : please update the ticket with information from the test of Esther. After that assign at max 2 persons for testing.

**Comment by schuelet** [comment]
- Esther had issues with running a model in a deprecated workflow (1): [https://seafile.bfr.berlin/d/0b585e100fd946e98cf8/files/?p=%2FFSK-Lab_20201009.docx](https://seafile.bfr.berlin/d/0b585e100fd946e98cf8/files/?p=%2FFSK-Lab_20201009.docx)
  - The workflow loaded as intended though.
- Esther had issues with creating a model using .xlsx files as resources (2.) : [https://seafile.bfr.berlin/d/0b585e100fd946e98cf8/files/?p=%2FFSK-Lab_20201009.docx](https://seafile.bfr.berlin/d/0b585e100fd946e98cf8/files/?p=%2FFSK-Lab_20201009.docx) 
  - This could not be reproduced. Creator loads resource files as intended.
