### ISSUE TITLE
Release Candidate 3 for v.1.9.0 (KNIME 3) ready for testing

### ISSUE THREAD

**Issue by schuelet** [RakipInitiative/ModelRepository#157]
available here: [https://dl.bintray.com/fsk/1.9.0-rc3](https://dl.bintray.com/fsk/1.9.0-rc3)

- this is going to be the last build that still runs on KNIME 3.7.x and will replace the current ICPMF version
- support beyond this release is not planned
- new fixes/features:
  - deprecated nodes are packaged within FSK-Lab
  - legacy nodes feature (deprecated nodes) is only necessary if updating from old icpmf AND legacy feature was installed already
  - FSK-Lab should auto install required R packages on Mac
  - Joiner problems should be gone
  - files generated by model should be used as expected when joining
  - generated files should show up in the archive when writing the model to fskx after executing it.

- all test workflows available under KNIME server (external) /FSKX_Testing/FSK-Lab_1.9
- keep in mind, some old workflows load with errors and/or need to be reset before running, this is not fixable

**Comment by ahmadswaid** [comment]
@miguelalba what is the branch name on Github for this build.
Ist the 1.9.0-rc3_final or 1.9.0-rc3 ?

**Comment by miguelalba** [comment]
@ahmadswaid the final one. @schuelet added fixes from FSK-Lab 2 to the 1.9.0 branch https://github.com/SiLeBAT/FSK-Lab/commits/1.9.0-rc3_final

@RakipInitiative/rakip-members we should remove finish the QA of old builds and branches so we can remove them. There are too many open.

**Comment by miguelalba** [comment]
@ahmadswaid has the PR https://github.com/SiLeBAT/FSK-Lab/pull/716 the changes for this ticket? If so, we can move this ticket to QA.

**Comment by schuelet** [comment]
Here is the original workflow that Matthias wants to get working: 
[https://app.zenhub.com/files/241333403/fb898916-df34-48cd-ac4b-d5810b7be5f9/download](https://app.zenhub.com/files/241333403/fb898916-df34-48cd-ac4b-d5810b7be5f9/download)

**Comment by ahmadswaid** [comment]
Here is also a workflow shared by Matthias containing old setting files for which I added the most recent migration code.
https://seafile.bfr.berlin/f/6e84bfd933074036bd3e/

**Comment by ahmadswaid** [comment]
I think I should mention here the workflow shared by Matthias in this ticket:
https://app.zenhub.com/workspaces/online-model-repository-5e4bc0198f780f014bf8f3f3/issues/rakipinitiative/modelrepository/131

**Comment by schuelet** [comment]
It seems, my above statement was incorrect. That workflow can't be loaded by ICPMF either, so I have to assume it was created with some intermediate unreleased version. @ahmadswaid : Disregard this workflow then and concentrate only on workflows or models that actually work in ICPMF. We provide compatibility with released versions, that is all we can hope for.

**Comment by ahmadswaid** [comment]
I get the old joining icpmf workflow shared by Marcel:
https://drive.google.com/file/d/1gVEqlCZohe6YBKo-Tcr3EsmNJDOmhQkn/view?usp=sharing
The workflow is working fine, runner is generating the same plot as  the one we get from the FSK-Lab ICPMF version.
I tested that using the branch of the PR https://github.com/SiLeBAT/FSK-Lab/pull/719

**Comment by schuelet** [comment]
1.9.0 release candidate is online and ready for testing. I updated this ticked (see ticket description up top).

@mfilter and @ganasp : you can use the workflows available on the external KNIME server (see up top). Lars sent the login information on 5.11.2020 if you don't have admin rights.
