### ISSUE TITLE
integrate Renjin into landing page backend

### ISSUE THREAD

**Issue by miguelalba** [RakipInitiative/ModelRepository#164]
include dependencies in pom file
run tests

PR: https://github.com/RakipInitiative/landingpage-backend/pull/1

**Comment by miguelalba** [comment]
PR: https://github.com/RakipInitiative/landingpage-backend/pull/1

**Comment by schuelet** [comment]
The renjin library seems to not support the complete api for functions related to plotting images. 
We may have to wait until they fix those issues in a later release.
For now, I put it in the Icebox.

**Comment by schuelet** [comment]
Abandoned. If renjin is feature complete one day, we might revisit this.
