### ISSUE TITLE
editor js view not working with different model classes

### ISSUE THREAD

**Issue by schuelet** [RakipInitiative/ModelRepository#199]
Models other than the generic ones do not show up properly in the editor js view. There seem to be 2 errors:

- The codeMirror doesn't load because the textArea is not available in the html-element. 
- Only the scripts are loaded but not the metadata. 

The problem might be coming from errors in package de.bund.bfr.knime.js, specifically app_1.0.0.js or editor_data_1.0.0.js

**Comment by schuelet** [comment]
[https://app.zenhub.com/files/241333403/cc391f12-50b8-4c78-a6dd-86f16aaca944/download](https://app.zenhub.com/files/241333403/cc391f12-50b8-4c78-a6dd-86f16aaca944/download)

**Comment by ahmadswaid** [comment]
I think so, that could be missed support of other model classes in the new app libraries.
I will take over this.

**Comment by ahmadswaid** [comment]
Please re-evaluate the status now after I pushed this commit: 
https://github.com/SiLeBAT/FSK-Lab/commit/c85df7d95552cfb9d7edc02f281eb35bb1302530

I don't see any problem with loading the scripts and the codeMirror component, please reopen if a problem is still there.
