### ISSUE TITLE
editor parameter type error when not changing 

### ISSUE THREAD

**Issue by schuelet** [RakipInitiative/ModelRepository#201]
if a parameter is added in the editor (AFTER having already added one), not clicking on the parameter classification field and selecting INPUT or OUTPUT or CONSTANT results in an execution error bricking the editor node completely. The value seems to be a concatination by default: 

ERROR FSK Editor JS        2:8        Execute failed: Can not deserialize value of type de.bund.bfr.metadata.swagger.Parameter$ClassificationEnum from String "CONSTANTINPUTOUTPUT": value not one of declared Enum instance names: [OUTPUT, INPUT, CONSTANT]

Assuming one wants to add two output parameters in a row, the second time the user might not click on the classification field because it is already set to OUTPUT.

**Comment by schuelet** [comment]
Pull Request #756 under review

**Comment by schuelet** [comment]
Error still there if I add two output parameters in a row without changing the select-box.

[issue201.zip](https://github.com/RakipInitiative/ModelRepository/files/5943048/issue201.zip)


ERROR FSK Editor JS        2:34       CODING PROBLEM	NodeView.modelChanged() causes NullPointerException during notification of a changed model, reason: null
ERROR FSK Editor JS        2:34       Execute failed: Can not deserialize value of type de.bund.bfr.metadata.swagger.Parameter$ClassificationEnum from String "CONSTANTINPUTOUTPUT": value not one of declared Enum instance names: [OUTPUT, INPUT, CONSTANT]
 at [Source: N/A; line: -1, column: -1] (through reference chain: de.bund.bfr.metadata.swagger.GenericModel["modelMath"]->de.bund.bfr.metadata.swagger.GenericModelModelMath["parameter"]->java.util.ArrayList[2]->de.bund.bfr.metadata.swagger.Parameter["classification"])

**Comment by ahmadswaid** [comment]
@schuelet I can't reproduce the error anymore on my side.
you should see after changing to the new branch in the status bar in eclipse that some build is happening and that will generate the app.js file which is used in the end in the js nodes.
could you wait untill it finish build and the reset you node or use a new one (I use the debug mode)
If you don't see that status bar of building the app.js you can also do a maven build and that will by sure generate the file

**Comment by schuelet** [comment]
@ahmadswaid I see, didn't realize how it was supposed to work. Do I need to have grunt installed on my machine though? I seem to get the following error messages in the console:



'"node"' is not recognized as an internal or external command,
operable program or batch file.

Auto detecting Grunt for folder de.bund.bfr.knime.js failed with error: Error: Command failed: node_modules\.bin\grunt.cmd --help --no-color
'"node"' is not recognized as an internal or external command,
operable program or batch file.

'"node"' is not recognized as an internal or external command,
operable program or batch file.

Auto detecting Grunt for folder de.bund.bfr.knime.js failed with error: Error: Command failed: node_modules\.bin\grunt.cmd --help --no-color
'"node"' is not recognized as an internal or external command,
operable program or batch file.


'"node"' is not recognized as an internal or external command,
operable program or batch file.

Auto detecting Grunt for folder de.bund.bfr.knime.js failed with error: Error: Command failed: node_modules\.bin\grunt.cmd --help --no-color
'"node"' is not recognized as an internal or external command,
operable program or batch file.

'"node"' is not recognized as an internal or external command,
operable program or batch file.

Auto detecting Grunt for folder de.bund.bfr.knime.js failed with error: Error: Command failed: node_modules\.bin\grunt.cmd --help --no-color
'"node"' is not recognized as an internal or external command,
operable program or batch file.


'"node"' is not recognized as an internal or external command,
operable program or batch file.

Auto detecting Grunt for folder de.bund.bfr.knime.js failed with error: Error: Command failed: node_modules\.bin\grunt.cmd --help --no-color
'"node"' is not recognized as an internal or external command,
operable program or batch file.

'"node"' is not recognized as an internal or external command,
operable program or batch file.

Auto detecting Grunt for folder de.bund.bfr.knime.js failed with error: Error: Command failed: node_modules\.bin\grunt.cmd --help --no-color
'"node"' is not recognized as an internal or external command,
operable program or batch file.

**Comment by schuelet** [comment]
I let Maven run and even installed the locally created repository in a fresh KNIME 4. I also double checked if the code changes appear in the app.js. It is all there and the issue remains.

It occurs when adding an output parameter directly after adding another one and not switching/clicking-on the Classification select box.

**Comment by schuelet** [comment]
Successfully tested PR #756
