### ISSUE TITLE
Joiner Bug: Parameter suffixes are in wrong order

### ISSUE THREAD

**Issue by schuelet** [RakipInitiative/ModelRepository#205]
The suffixes for parameters are in the wrong order. This is only noticeably when joining >2 models: The error occurs in the editor.js when suffixes are applied.

Combined Model: 

`modelMath" : {
    "parameter" : [ {
      "id" : "x11",                                    
      "classification" : "INPUT",
      "name" : "x",

    }, {
      "id" : "out11",
      "classification" : "OUTPUT",
      "name" : "out",

    }, {
      "id" : "out12",                          <--        SHOULD BE : "out21" 
      "classification" : "OUTPUT",
      "name" : "out",
  
    }, {
      "id" : "out2",
      "classification" : "OUTPUT",
   
  }`

In this instance model3 is joined with (model1 + model2), therefore it gets the suffix "2" whereas (model1 + model2) get the suffix "1".  The correct order of execution would be:
first: model11
second: model21
third: model2

Joined with another model4 it would be:
first: model111
second: model211
third: model21
fourth: model2

**Comment by ahmadswaid** [comment]
@schuelet  could you please share the workflow

**Comment by schuelet** [comment]
[https://app.zenhub.com/files/241333403/f48dc957-7700-45d5-8b09-7ba2e4d653c4/download](https://app.zenhub.com/files/241333403/f48dc957-7700-45d5-8b09-7ba2e4d653c4/download)

**Comment by ahmadswaid** [comment]
I don't agree with the assumption:
`"id" : "out12",                          <--        SHOULD BE : "out21" `

I see the suffixing is correct at least from the design point of view.
I read the suffix from left to right:
so please see my annotation:
`"modelMath" : {
"parameter" : [ {
"id" : "x11",                           <--        first joined, first model
"classification" : "INPUT",
"name" : "x",

}, {
  "id" : "out11",                      <--        first joined,  first model
  "classification" : "OUTPUT",
  "name" : "out",

}, {
  "id" : "out12",                       <--       first joined,  second model
  "classification" : "OUTPUT",
  "name" : "out",

}, {
  "id" : "out2",                      <--         second model
  "classification" : "OUTPUT",

}`

the joiner which has four input will join the first two and generate the first joined model which will be joined with the third and after that the fourth and so the fourth model is the second model and the generated combined model from the first three is the first model and so on.

saying that the suffix should be like:
first: model111
second: model112
third: model12
fourth: model2

**Comment by schuelet** [comment]
I see. The Runner used to take the last suffix from each parameter. If it was 1, the parameter belonged to the first model and if 2 then it belonged to the second one. 
I guess your way could work as well, I just have to get my head around it. I just wonder why the Runner doesn't work for me with my test models.

**Comment by schuelet** [comment]
after conferring with Ahmad we agreed to close this ticket since it is a design decision and not a bug.

**Comment by ahmadswaid** [comment]
for the point of left to right suffixing:
it's important to notice that the algorithm which adds these suffixes is recursive one which will start to add suffix from deepest node (if I may say) to the top ones and which will accumulates at the end in the way you see and can be read from left to right
