### ISSUE TITLE
assignment of join relation error

### ISSUE THREAD

**Issue by schuelet** [RakipInitiative/ModelRepository#210]
The joinRelation is not correctly assigned when executing combined models.

**Comment by ahmadswaid** [comment]
@schuelet I think I fixed the issue wrong assignment and another one also related to the cascade joining but also related the same main issue here.
Could please test again.

**Comment by ahmadswaid** [comment]
@schuelet  solution was pushed to https://github.com/SiLeBAT/FSK-Lab/tree/Assignment_of_join_relation branch

**Comment by schuelet** [comment]
@ahmadswaid I tested it, it works fine. Thanks very much. You can merge or create a pull request if you want, I take care of it.

**Comment by schuelet** [comment]
[https://app.zenhub.com/files/241333403/7c7951d7-6bd3-4cef-b076-7a48dd943ad9/download](https://app.zenhub.com/files/241333403/7c7951d7-6bd3-4cef-b076-7a48dd943ad9/download)
