### ISSUE TITLE
Test Joiner: Join Command

### ISSUE THREAD

**Issue by schuelet** [RakipInitiative/ModelRepository#211]
Create a workflow that uses a complex join command to verify it is applied as intended.

**Comment by schuelet** [comment]
[https://app.zenhub.com/files/241333403/384f75a6-4e56-4bb8-9370-66bc55b47da5/download](https://app.zenhub.com/files/241333403/384f75a6-4e56-4bb8-9370-66bc55b47da5/download)

Successfully tested the application of the Join Command. Workflow attached.

**Comment by mfilter** [comment]
add workflow to KNIME Server WF test repository

**Comment by schuelet** [comment]
WF on external server: knime://external-KNIME-Server/FSKX_Testing/FSK-Lab_2.0/Joiner_Test_JoinCommand
