### ISSUE TITLE
Test Joiner: Input to Input

### ISSUE THREAD

**Issue by schuelet** [RakipInitiative/ModelRepository#212]
Create a workflow that joins models by joining input parameters of one model with input parameters of another.

**Comment by schuelet** [comment]
Stress test completed. Workflow attached.

[https://app.zenhub.com/files/241333403/5b513485-fe05-4b5f-b4ec-ec3e5ce51c4b/download](https://app.zenhub.com/files/241333403/5b513485-fe05-4b5f-b4ec-ec3e5ce51c4b/download)

**Comment by mfilter** [comment]
add workflow to KNIME Server WF test repository

**Comment by schuelet** [comment]
WF on external server: knime://external-KNIME-Server/FSKX_Testing/FSK-Lab_2.0/Joiner_Test_InputToInput
