### ISSUE TITLE
Joiner Test: add simulation to joined model

### ISSUE THREAD

**Issue by schuelet** [RakipInitiative/ModelRepository#213]
Create a workflow that joines models and add  a simulation via simulation configurator to the model to make sure, the values are correctly apllied.

**Comment by schuelet** [comment]
Test successful. Workflow attached. 

[https://app.zenhub.com/files/241333403/8bd90e45-46e1-4fa7-abb9-adf910a934fd/download](https://app.zenhub.com/files/241333403/8bd90e45-46e1-4fa7-abb9-adf910a934fd/download)

**Comment by mfilter** [comment]
add to WF to KNIME server WF test repository

**Comment by schuelet** [comment]
WF on external server: knime://external-KNIME-Server/FSKX_Testing/FSK-Lab_2.0/Joiner_Test_addSimulation
