### ISSUE TITLE
Runner/Writer: Handle the output of combined models

### ISSUE THREAD

**Issue by schuelet** [RakipInitiative/ModelRepository#217]
Right now, parameters (input & output) and generated resources of each simple model will be saved and stored in its corresponding fskx file. 

Combined models have an output too, though. If one thinks of a combined model as a black box, then it stands to reason, that it should have parameters and resource files of their own, i.e. in their own folder. **This becomes relevant when thinking about visualizing execution results & data of combined models.**

Find a way for combined models (at least top level) to store the input and output parameters in a separate JSON file. Generated files should also be available somehow.

**Comment by schuelet** [comment]
Since this would require changing the portObject, we should not attempt this at the moment. I also think the current solution, to have a flow variable in the Runner pointing to the generated Resource folder containing the parameters.json, works fine. All files generated by individual models will show up in the fskx file in their correspondent folders.

Putting it on ice.

**Comment by ahmadswaid** [comment]
@schuelet As discussed the resources of combined models end up in the last model run in the chain.
closing this ticket as of a solution is in place already.
