### ISSUE TITLE
Test combined Models: data types

### ISSUE THREAD

**Issue by schuelet** [RakipInitiative/ModelRepository#224]
Create models containing parameters of the following data types:

- numeric
- string
- array (vector and matrix)
- list
- dataframe

- create models for Python and R
- join models

**Comment by schuelet** [comment]
Tests successful.

Workflow attached.[https://app.zenhub.com/files/241333403/07b0e807-4869-4e51-8c65-217132c618ac/download](https://app.zenhub.com/files/241333403/07b0e807-4869-4e51-8c65-217132c618ac/download)

**Comment by mfilter** [comment]
Provide WF on KNIME server

**Comment by schuelet** [comment]
WF on external server: knime://external-KNIME-Server/FSKX_Testing/FSK-Lab_2.0/Test_Comb_Models_data_types
