### ISSUE TITLE
Editor node should use native KNIME requests

### ISSUE THREAD

**Issue by miguelalba** [RakipInitiative/ModelRepository#231]
~~The editor node should use the native KNIME requests introduced in https://github.com/SiLeBAT/FSK-Lab/pull/771. This 
removes the need to configure the Content Security Policy and fixes the vocabularies on the server.~~
The JS view of the editor node is loading the controlled vocabularies as part of the view representation.

- [X] The editor node must be tested on a server not hosted locally.
- [x] The old requests in FskService related to the vocabularies must be removed.

@ahmadswaid can we remove the endpoints in FskService for serving vocabularies? Are they used in any other JS view or DB component?

**Comment by mfilter** [comment]
Please check this and decide how to proceed

**Comment by ahmadswaid** [comment]
@miguelalba yes, It can be removed. no cleint is using them now.
but I think we should close this ticket here as it will not work for the server (the way of native knime request) and creat another one for cleaning up of js code and the removal of FskService vocabularies endpoint .
