### ISSUE TITLE
Joiner node should use native KNIME requests

### ISSUE THREAD

**Issue by miguelalba** [RakipInitiative/ModelRepository#232]
The joiner node calls FskService for combining and joining metadata and these calls do not work on a server as they are performed locally instead of the server.

# Requests in backend
The two calls are similar. JsonViewRequestHandler only supports one request and one response. Combining and joining returns a single model metadata so the response may contain a single *Model* object. The requests may need more tinkering but should be doable with optional properties.

This feature should be implemented after developing the schemas as the new ones won't have third party libraries (ThreeTenDate) that would cause problems with the ObjectMapper.

**Comment by mfilter** [comment]
@ahmadswaid : please check and decide if this is relevant or can be closed

**Comment by ahmadswaid** [comment]
close, as the current implementation use the JS side to combine models metadata.
