### ISSUE TITLE
Update joining algorithm for new schema

### ISSUE THREAD

**Issue by miguelalba** [RakipInitiative/ModelRepository#242]
The joining algorithm is used in the joiner (and DB view component?). Same situation as with the model conversion algorithm.

**Comment by mfilter** [comment]
@ahmadswaid : please explore what is meant here. If this is related to the new FSKX and metadata schema v1.05 it receives low prio, as we first have to fix the issue with the next release candidate that will still use v1.04.

**Comment by ahmadswaid** [comment]
close, as the joining algorithm is implemented in the JS side and no extra maintenance is needed to support new schemas in the futute.
