### ISSUE TITLE
Expose model conversion algorithm with KNIME requests API

### ISSUE THREAD

**Issue by miguelalba** [RakipInitiative/ModelRepository#243]
The current implementation with the FskService does not work on the server. Implement it like in the Javascript Table View. See https://github.com/SiLeBAT/FSK-Lab/pull/771/

**Comment by mfilter** [comment]
@ahmadswaid : please check if this is an issue and decide on how to proceed.

**Comment by ahmadswaid** [comment]
close, as the joining algorithm is implemented in the JS side
