### ISSUE TITLE
Component Bug: Execution fails (unrecognizedPropertyException)

### ISSUE THREAD

**Issue by schuelet** [RakipInitiative/ModelRepository#245]
Picking qmra salmonella model from DB View and joining it with others works.
Picking any other models from the DB View and joining them results in an UnrecognizedPropertyException. 

[https://app.zenhub.com/files/241333403/f2797ef1-8264-4370-89f0-8615f05740f8/download](https://app.zenhub.com/files/241333403/f2797ef1-8264-4370-89f0-8615f05740f8/download)

![image.png](https://images.zenhubusercontent.com/5e4ba30f8f780f7f48f8f306/1055cc6c-e0e4-432d-97f2-27499a60ce2d)

**Comment by ahmadswaid** [comment]
I will take care of it.
It's seems to be a bug with join method of the ConversionUtils class

**Comment by schuelet** [comment]
fixed.
