### ISSUE TITLE
Apply new UI to KNIME model repository

### ISSUE THREAD

**Issue by schuelet** [RakipInitiative/ModelRepository#254]
The table view in the KNIME online model repository has still the old UI. It needs an update.

**Comment by schuelet** [comment]
The model reposoitory main table view on the KNIME Server needs the new UI and possible some metadata updates. 
Code is here: https://github.com/SiLeBAT/knimeserver

It is basically the landingpage but as a KNIME node. We need to discuss the implementation in a next meeting. Because it uses a workflow to populate the table, it might require special attention.

**Comment by mfilter** [comment]
I strongly suggest to use -if possible- the new DB View node that Ahmad created.

**Comment by schuelet** [comment]
@ahmadswaid one of the workflows that use the "Web repository node" (https://dl.bintray.com/silebat/lars) is this: knime://external-KNIME-Server/FSK-Web/1._FSK_Model_Repository_Demonstrator

Our models are here:
knime://external-KNIME-Server/FSK-Web/newfiles
knime://external-KNIME-Server/RAKIP-Web/newfiles

shared testing workflows are here:
knime://external-KNIME-Server/FSKX_Testing/FSK-Lab_2.0
