### ISSUE TITLE
Component bug: cropped Joiner View

### ISSUE THREAD

**Issue by schuelet** [RakipInitiative/ModelRepository#257]
- Resetting an executed Component. 
- Execute and open View

--> Joiner View is cropped, although it still seems to work.

[https://app.zenhub.com/files/241333403/10ee31db-025d-444a-8cc0-2f838cc36f22/download](https://app.zenhub.com/files/241333403/10ee31db-025d-444a-8cc0-2f838cc36f22/download)

![image.png](https://images.zenhubusercontent.com/5e4ba30f8f780f7f48f8f306/7d342f46-c525-490f-a8c9-79c80dbc7346)

**Comment by ahmadswaid** [comment]
I can reproduce the issue, I'm on it

**Comment by mfilter** [comment]
please close the ticket if it is solved

**Comment by ahmadswaid** [comment]
fixed
