### ISSUE TITLE
simulator bugs: parameter of type double bugged

### ISSUE THREAD

**Issue by schuelet** [RakipInitiative/ModelRepository#264]
- Double Parameter with min & max value defined are not correctly shown (only min value is shown)
- If a parameter (double) has no min or max value, changing the value enforces conversion to integer

Fixes need to be applied to FSK-Lab app.js and landingpage app.js

[https://app.zenhub.com/files/241333403/a60b5652-02c2-4211-9bf4-d5a8e254764b/download](https://app.zenhub.com/files/241333403/a60b5652-02c2-4211-9bf4-d5a8e254764b/download)

**Comment by schuelet** [comment]
Sascha fixed the UI bugs and I applied it to FSK-Lab & LandingPage.

**Comment by schuelet** [comment]
@ganasp Can you also check if the issue with missing Simulations still applies? If so, please log the steps so I can recreate the issue.Thanks.

**Comment by ganasp** [comment]
Testing fsklab.feature_2.0.0.202103090921:
1) Creating new simulation with adjustment of parameter values, which have the type double
Problem: old value is 1.0 or 0.0, new value should be 1.23, 0.84 or 0.86, but it is only possible to get new value of 1.2, 0.8 or 0.9 
The new value of a parameter will be automatically adjusted with only one decimal place by rounding.
2) FSKX model with different predefined simulation settings, only default simulation is still available after FSKX Reader->FSK Editor->FSKX Writer
The problem still applies. Also if the FSK Editor Node is only executed, NOT execute and open views, after writing the model in a new FSKX file, this file contains only the default simulation, all the other simulations are missing.

**Comment by schuelet** [comment]
issue 2 is documented in RakipInitiative/ModelRepository#183
