### ISSUE TITLE
scriptHandler bug: R path to user libraries are removed

### ISSUE THREAD

**Issue by schuelet** [RakipInitiative/ModelRepository#270]
- installLibs() checks if new packages need to be installed but ALSO adds the .fsk folder  to libPaths
- restoreDefaultLibrary() drops the first entry in .libPaths
- installLibs() is skipped if no new libraries are present but restoreDefaultLibrary still runs, thus removing potential user folders from .libPaths

**Comment by schuelet** [comment]
Here the workflow that showcases the issue (internal link) https://seafile.bfr.berlin/smart-link/5e75119b-f080-4f96-b785-26dcca8e3f3f/

**Comment by mfilter** [comment]
please close this ticket if it is solved

**Comment by schuelet** [comment]
it is fixed. Closing.
