### ISSUE TITLE
Reader issue: model archive from URL is deleted too soon

### ISSUE THREAD

**Issue by schuelet** [RakipInitiative/ModelRepository#276]
If a model is loaded by the Reader using a URL, a temporary file is created storing the archive to create a portObject. Then the archive is deleted. 
But the Runner requires the archive to execute the model. 

I believe, the archive should be stored for longer, and only be deleted on reset.

@ahmadswaid since I think you implemented this download from URL system, I am assigning you to it. You can assign it to me if you don't want to do it, though.

[https://app.zenhub.com/files/241333403/d87c0ecc-9bd9-47af-82e2-a384954e3b66/download](https://app.zenhub.com/files/241333403/d87c0ecc-9bd9-47af-82e2-a384954e3b66/download)

**Comment by schuelet** [comment]
fixed in https://app.zenhub.com/workspace/o/silebat/fsk-lab/issues/804.  

Testing required, if issues occur when a workflow is shared across different operating systems.

**Comment by schuelet** [comment]
@mfilter I was thinking about sharing workflows with this and I don't see an easy way to avoid re- executing the reader. Here is the rundown:
- Reader has the URL in settings, downloads the model, PortObject will get the absolute local path to the model
- workflow is saved
- on opening on another PC, the PortObject **still** has the path of the original PC, thus the Reader must be re-executed otherwise any other node will try to access that original path.

I was experimenting with the knime:// Protocoll in the hope that might be an easy solution. I think, if the user uses the Protokoll (or the download from URL option), then we have the guaranteed model path and could avoid the forced re-execution. When I have time, I will implement it.

**Comment by mfilter** [comment]
OK, I change the prio to medium. My assumption is, that the URL-based models are downloaded into a folder inside the WF that has the Reader is in, correct?

**Comment by schuelet** [comment]
yes, the user has the files in the workflow folder and can access them if they don't want to re-download them.

**Comment by schuelet** [comment]
@ahmadswaid maybe we can rename the downloaded model files at some point so they can be identified by the user.

**Comment by ahmadswaid** [comment]
@schuelet,  
yes, one Idea come to my mind is using the enveiroment manager to resolve the knime:// into a real path just in time.
then we don't need to re-run the reader node
