### ISSUE TITLE
add a checkbox to Runner to toggle storing of output parameters in JSON file

### ISSUE THREAD

**Issue by schuelet** [RakipInitiative/ModelRepository#277]
The Runner will have a checkbox (default: off) stating if the model parameters should be written out into a JSON file. This is done because for R models with a lot of parameters, saving the parameters is very time consuming.

User feedback required, if the checkbox should be set to "on" by default.

**Comment by schuelet** [comment]
PR in SiLeBAT/FSK-Lab/#797

**Comment by mfilter** [comment]
I'm fine with the proposed toggle setting (default: off). Only, in the case of execution a joined models this setting must be automatically switched to ON.
