### ISSUE TITLE
Editor vocabularies bug: language_written_in missing

### ISSUE THREAD

**Issue by schuelet** [RakipInitiative/ModelRepository#288]
The vocabularies for language_written_in are not loaded, instead language is taken: 
![image.png](https://images.zenhubusercontent.com/5e4ba30f8f780f7f48f8f306/232af33b-3b6f-45ba-b50c-0ff20595df69)

**Comment by miguelalba** [comment]
Please check PR https://github.com/SiLeBAT/FSK-Lab/pull/816 and close this ticket.
