### ISSUE TITLE
editor Classification enum bug: editing parameter without touching classification concatenates enum

### ISSUE THREAD

**Issue by schuelet** [RakipInitiative/ModelRepository#290]
Editing existing parameter: only change value, leave everything as it is -> save parameter:

![image.png](https://images.zenhubusercontent.com/5e4ba30f8f780f7f48f8f306/e002890c-f6ed-4241-9117-a296fef6f042)

**Comment by ahmadswaid** [comment]
@schuelet 
I was not able to reproduce that behaviour on widows (KINME 4.0) or Mac (KNIME 4.2) in both component or alone editor use cases.

**Comment by schuelet** [comment]
Strange, I can't reproduce it either, maybe a previous bugfix helped. I will close this ticket then.
