### ISSUE TITLE
editor bug: cant edit more than one item in a list

### ISSUE THREAD

**Issue by schuelet** [RakipInitiative/ModelRepository#296]
have a model with 2+ parameters > editor -> change both of them -> only last edited parameter is saved

**Comment by ahmadswaid** [comment]
@schuelet I can't reproduce it with the development branch, on both window (KNIME 4.0) or Macos (4.2)

**Comment by schuelet** [comment]
@ahmadswaid you're right, for the parameters that doesn't apply, but for some reason it does for the references and I assumed for 
 other arrays as well.

**Comment by ahmadswaid** [comment]
fix in https://github.com/SiLeBAT/FSK-Lab/pull/829

**Comment by mfilter** [comment]
as it was reported by @ganasp there is still a small issue with the editor node, where the user needs to provide an email address for each author entry, which is not always possible or useful. It would be useful if we could relax this constraint for the entries in the author fields.

**Comment by schuelet** [comment]
email validation removed in https://github.com/SiLeBAT/FSK-Lab/pull/835
