### ISSUE TITLE
editor bug: creation date starts at 0

### ISSUE THREAD

**Issue by schuelet** [RakipInitiative/ModelRepository#301]
the creation date (and possible other dates) starts counting at 0 (zero) instead of 1, thus if one choses March, it will display February.

![image.png](https://images.zenhubusercontent.com/5e4ba30f8f780f7f48f8f306/fb42c153-66f4-4da1-8311-ee1d301cb121)

**Comment by ahmadswaid** [comment]
@schuelet I fixed that in https://github.com/SiLeBAT/FSK-Lab/pull/829 . could you please confirm.

**Comment by schuelet** [comment]
@ahmadswaid yes, can confirm that it was fixed. I used the older version on the test server. Sorry for that.
