### ISSUE TITLE
FSK_Repository_Model_Runner workflow error: "scope start and end nodes not in same workflow"

### ISSUE THREAD

**Issue by schuelet** [RakipInitiative/ModelRepository#303]
@llavall I was trying to update the Runner workflow for FSK-Web and keep getting this error. This happens in the original untouched workflow as well, locally and on the server.

![image.png](https://images.zenhubusercontent.com/5e4ba30f8f780f7f48f8f306/0bf1008f-3a49-4d9d-aa51-0b4476660d10)

**Comment by schuelet** [comment]
@llavall I found the issue, apparently KNIME now complains if the try node is in a metanode ("FSK Reader" in the workflow). I put it outside and it works fine.

**Comment by llavall** [comment]
Great
