### ISSUE TITLE
Joiner bug: svg not valid in KNIME report

### ISSUE THREAD

**Issue by schuelet** [RakipInitiative/ModelRepository#309]
The Joiner Image seems to contain characters that the KNIME report can't deal with. 
A workflow where this can be observed can be found here:
knime://external-KNIME-Server/FSKX_Testing/FSK-Lab_2.0/broken_workflows/Joiner_Report_Issue

![image.png](https://images.zenhubusercontent.com/5e4ba30f8f780f7f48f8f306/5263af7a-8ae7-487f-b7ce-9f9752bca9b4)

**Comment by ahmadswaid** [comment]
@schuelet: the problem exist only on knime desktop of windows. it's working good on MacOS and Ubunto.
Have you tried to generate the report on the new kinme server as it's running on Linux.
Anyway I will try to fix it for windows!
<img width="1783" alt="Screenshot 2021-04-07 at 20 52 31" src="https://user-images.githubusercontent.com/4013295/113918959-51c27180-97e3-11eb-9777-5a899eba1a32.png">

**Comment by llavall** [comment]
@ahmadswaid The problem became prominent under Linux Debian 9. 
Ubuntu and even a more recent version might not show that. Hopefully, the solution for Windows will also fix it for Debian.

**Comment by ahmadswaid** [comment]
Debian 9: 
<img width="1792" alt="Screenshot 2021-04-08 at 20 48 56" src="https://user-images.githubusercontent.com/4013295/114080799-1770d700-98ac-11eb-9465-c98ff3ad6904.png">
Windows:
<img width="1792" alt="Screenshot 2021-04-08 at 22 51 10" src="https://user-images.githubusercontent.com/4013295/114094778-ffee1a00-98bc-11eb-8996-d178a5869ed5.png">
KNIME Server (Ubunto):
<img width="1792" alt="Screenshot 2021-04-08 at 22 52 34" src="https://user-images.githubusercontent.com/4013295/114094959-3330a900-98bd-11eb-902a-783a207e138e.png">

**Comment by schuelet** [comment]
I tested it as well and will close it.
