### ISSUE TITLE
missing error block and failing model

### ISSUE THREAD

**Issue by llavall** [RakipInitiative/ModelRepository#318]
I made some discoveries I do not really understand. I explain my findings in the WF.

knime://knime.mountpoint/FSKX_Testing/FSK-Lab_2.0/broken_workflows/fail%20test

**Comment by mfilter** [comment]
@llavall : I just testet both runners locally and none of them now threw an error. Could you please check again for the server? Thx.
BTW: I can reproduce the warning message from the the current Runner: 
"WARN  FSK Runner           0:924      WARNING: FILE parameter 'c(data)' of model 'PiresOutbLA2011-Salmonella' is not accessible as a filename. Make sure the variable is global and check its value. File parameters should only have their file name + extension as a value"

There are **2 interesting findings here:**
1.: there is no "c(data) " in the file name, but the warning indicates, that the way how the default value for the file name Input parameter was given is not the correct way (it is actually an R command and not a file name, as we would expect now with the UI checks) => so I think this warning is indeed helpful.
@ganasp : when this model "201912090707_PiresOutbLA2011-Salmonella.fskx" is updated, this should be fixed.
2:@ahmadswaid: I notiiced that I can not open this model with the editor anymore. I captured the following error from the Editor JS side: Maybe you can have a look? (I know this is a different problem class).
Failed to load resource: net::ERR_FILE_NOT_FOUND
knime_service_1_0_0.js:1 Failed to load resource: net::ERR_FILE_NOT_FOUND
js-lib/knime/service/knime.css:1 Failed to load resource: net::ERR_FILE_NOT_FOUND
jquery-3.3.1.min.js:1 Failed to load resource: net::ERR_FILE_NOT_FOUND
require.js:1 Failed to load resource: net::ERR_FILE_NOT_FOUND
knime_service_load_conditionally.js:1 Failed to load resource: net::ERR_FILE_NOT_FOUND
knime_service_lazy_loading_loader.js:1 Failed to load resource: net::ERR_FILE_NOT_FOUND
app_1.0.0.js:12 Uncaught TypeError: Bootstrap's JavaScript requires jQuery. jQuery must be included before Bootstrap's JavaScript.
    at Object.jQueryDetection (app_1.0.0.js:12)
    at app_1.0.0.js:12
    at app_1.0.0.js:12
    at app_1.0.0.js:12
jQueryDetection @ app_1.0.0.js:12
(anonymous) @ app_1.0.0.js:12
(anonymous) @ app_1.0.0.js:12
(anonymous) @ app_1.0.0.js:12
bootstrap3-typeahead.min.js:1 Uncaught TypeError: Cannot read property 'fn' of undefined
    at bootstrap3-typeahead.min.js:1
    at bootstrap3-typeahead.min.js:1
    at bootstrap3-typeahead.min.js:1

**Comment by ahmadswaid** [comment]
@mfilter:
I can't reproduce the error 
<img width="1016" alt="image" src="https://user-images.githubusercontent.com/4013295/116793687-764ef800-aac8-11eb-9fbc-20f2793c76d1.png">
these libraries can't be loaded (ERR_FILE_NOT_FOUND) if they are not deployed correctly from knime. 
is this the way you connected the editor?
<img width="224" alt="image" src="https://user-images.githubusercontent.com/4013295/116793758-f8d7b780-aac8-11eb-8af7-466ef3a68300.png">

**Comment by mfilter** [comment]
Thanks for testing. I now tried again, and can't reproduce myself. Sorry for that!
Probably , the restart of KNIME did the trick.

**Comment by mfilter** [comment]
@ahmadswaid : do you think the you can do something on the behaviour of the outports in case the Runner fails? As Lars requested?

**Comment by ahmadswaid** [comment]
@mfilter yes I think so. it's on my list

**Comment by llavall** [comment]
@mfilter you are right, the model selected to showcase the behavior in this example workflow does not shot errors anymore for me - neither local or on the server.
Therefore, I found an old faulty model and reuploaded the workflow and tried to improve the explanation what goes wrong. It looks like that all FSK nodes lack the blocking feature if the nodes are failing - only the ActiveBranchInverter-node is able to force that behavior. 
If I could have a workflow provided which is showing every FSK node failing individually in a reasonable way, I could create a functional test workflow to always check the functionality for that feature.

**Comment by ganasp** [comment]
The updated model 'PiresOutbLA2011-Salmonella' can be executed without problems. The model is listed in ModelRepository/FSK-Web.

**Comment by llavall** [comment]
The blocking issue seems to be fixed now - I will close this ticket and the old one.
