### ISSUE TITLE
Server issue: package libgsl-dev for Debian missing

### ISSUE THREAD

**Issue by schuelet** [RakipInitiative/ModelRepository#326]
The packages libgsl-dev needs to be installed manually so a model that uses the library "gsl" can be executed.
The second model in the workflow 
knime://external-KNIME-Server/FSKX_Testing/FSK-Lab_2.0/final_test_workflows/Test_deprecatedNodes_v1.9_with%20JoinerWF_ICPMF11_MF

requires this library.

On the Server, run the command:
>> sudo apt install libgsl-dev

**Comment by llavall** [comment]
@schuelet  the requested libgsl-dev is already installed on all servers - can not say how many years - this should not be a new issue?

**Comment by schuelet** [comment]
issue has been cleared with @llavall
