### ISSUE TITLE
Updatesite is suddenly 615MB big - was 315MB until some days ago?

### ISSUE THREAD

**Issue by llavall** [RakipInitiative/ModelRepository#327]
https://gitlab.bfr.berlin/silebat/repositories/-/archive/master/repositories-master.zip

**Comment by schuelet** [comment]
@miguelalba Is this related to gitlab saving multiple versions? Do we delete before we upload a new release?

**Comment by miguelalba** [comment]
> @miguelalba Is this related to gitlab saving multiple versions? Do we delete before we upload a new release?

There are two versions in two separate folders: development with the builds for every commit in the development branch and fsklab that contains releases.

@llavall When you download a zip version of the whole repository you are zipping both folders, hence the 600MB. Keeping the two update sites in the same repository was discussed in last call.

**Comment by llavall** [comment]
@miguelalba thanks for clarification. That means the link I am using to get fsklab is wrong. I don't know how to get the link for the raw version as zip. Can you confirm this one is more correct or is it the non working non raw version then? https://gitlab.bfr.berlin/silebat/repositories/-/archive/master/fsklab.zip

**Comment by miguelalba** [comment]
@llavall I split the repos. Please check and close the issue.

**Comment by llavall** [comment]
solved - THX!
