### ISSUE TITLE
Joiner bug: gropin models path not found

### ISSUE THREAD

**Issue by schuelet** [RakipInitiative/ModelRepository#344]
When trying to join any gropin models with the Component, the ERROR message:
`Execute failed: C:\Users\thsch\AppData\Local\Temp\knime_Online_Joining_55838\Gropin growth model for Listeria monocytogenes in\on Seafood salad (gropin ID: 467 ).fskx (The system cannot find the path specified)`

appears. It seems, the temporary file is stored using the model name instead of the model id.

@ahmadswaid Can I even assign you to new issues? If not, please mention it, it is not a problem.

**Comment by ahmadswaid** [comment]
@schuelet: of course you can, I will take care of it.
