### ISSUE TITLE
Editor bug: can't retrieve value from view

### ISSUE THREAD

**Issue by schuelet** [RakipInitiative/ModelRepository#346]
Clicking apply when editing the model in this workflow throws this error:

![image.png](https://images.zenhubusercontent.com/5e4ba30f8f780f7f48f8f306/ad0805e2-92ad-4242-a7f4-3b375c8c0abb)

The workflow is here: knime://external-KNIME-Server/FSKX_Testing/FSK-Lab_2.0/broken_workflows/Joining_TrichinellaModels

The first 3 models don't have a visualization script (by design). 

Are the models at fault or is it FSK-Lab?

**Comment by ahmadswaid** [comment]
@schuelet I can't reproduce the issue. the editor is able to to edit and save the metadata for all models in the shared workflow / tested that on Mac and Windows

**Comment by schuelet** [comment]
Fixed in https://app.zenhub.com/workspace/o/silebat/fsk-lab/issues/931
