### ISSUE TITLE
FSK editor table produces very tall almost empty cells

### ISSUE THREAD

**Issue by arno314** [RakipInitiative/ModelRepository#467]
Go to General Information -> Reference.
Make a change, I set 'is reference description' to yes.
When returning to the overview the just changed row has expanded enormously and consists of mostly white space.
![Screenshot from 2023-02-27 12-49-10](https://user-images.githubusercontent.com/104012484/221550229-03411638-7f3b-487c-ba39-4a151639ba9c.png)

**Comment by schuelet** [comment]
should be fixed.
