### ISSUE TITLE
Design Solution for Curation infrastructure

### ISSUE THREAD

**Issue by schuelet** [RakipInitiative/ModelRepository#85]
### base features:
- RAKIP members are:
  - informed about the new addition (e.g. by mail)
  - able to run the model in a save environment (e.g. VRE, Jupyter, Cloud, VM)
  - sharing their thoughts on the model with each other
  - proposing changes for the author/creator of the model (e.g. as a compiled list)
  - able to accept/deny/veto the admission of  the new model

### options
- KNIME Server solution
- stand alone Web application (ask Taras about his glossary project)

**Comment by schuelet** [comment]
@mfilter Not convinced that this is worth considering anymore. RAKIP meetings take care of the discussion/veto part in our experience. The RAKIP Models Overview Workflow (https://knime.bfr.berlin/knime/webportal/space/Model_Curation/RAKIP_Models_Overview)  keeps track on the progress and notes.

**Comment by mfilter** [comment]
agree
