### ISSUE TITLE
Prevent duplicate model names in repository

### ISSUE THREAD

**Issue by schuelet** [RakipInitiative/ModelRepository#98]
- two different models with the same name should not appear in the model repository.

**Comment by schuelet** [comment]
@mfilter If we give the models the Zenodo DOI like we have talked about, do you think we could allow duplicate model names? Zenodo and the VRE also allow entries with the same name.

**Comment by mfilter** [comment]
Good point. I think the names could be the same, but we need to have unique model IDs.
I also suggest to used the ZenodoDOI as a model ID and not as a model name.
HTH

**Comment by schuelet** [comment]
Alright very good. Closing this ticket then.
